# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Load csv
weather_file = "../WeatherPy/WeatherPY3.csv"

# Read and display csv with Pandas
weather_df = pd.read_csv(weather_file)
weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Dikson,73.5069,80.5464,-34.28,80,0,6.85,RU,1612053325
1,Lagoa,39.0500,-27.9833,61.90,94,100,25.64,PT,1612053391
2,Rikitea,-23.1203,-134.9692,79.50,70,0,11.34,PF,1612053307
3,Ushuaia,-54.8000,-68.3000,51.80,62,20,21.85,AR,1612053316
4,Punta Arenas,-53.1500,-70.9167,51.80,62,0,26.46,CL,1612053538

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# Store latitude and longitude in locations
locations = weather_df[["Lat", "Lng"]]
# locations
rating = weather_df["Humidity"].astype(float)

In [5]:
# Plot heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, dissipating=False, max_intensity=10, point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
hotel_df= weather_df[(weather_df["Max Temp"]>60) & (weather_df["Max Temp"]<=90) & (weather_df["Humidity"]>=30) & (weather_df["Humidity"]<=60) & (weather_df["Cloudiness"]<60)]
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
26,Busselton,-33.6500,115.3333,75.99,58,0,8.48,AU,1612053308
35,Acajutla,13.5928,-89.8275,80.60,54,20,5.79,SV,1612053354
60,Thayetmyo,19.3167,95.1833,66.00,45,57,1.30,MM,1612053549
61,Hobart,-42.8794,147.3294,73.00,40,20,11.50,AU,1612053549
102,Ahipara,-35.1667,173.1667,72.28,49,0,5.99,NZ,1612053557
103,Ratnagiri,16.9833,73.3000,73.20,50,2,5.84,IN,1612053557
107,Broken Hill,-31.9500,141.4333,77.00,38,8,13.80,AU,1612053557
118,Fortuna Foothills,32.6578,-114.4119,64.40,34,1,9.22,US,1612053560
122,Mildura,-34.2000,142.1500,75.00,53,0,9.22,AU,1612053560
153,Wanaka,-44.7000,169.1500,70.50,36,17,5.99,NZ,1612053566
156,Makkah al Mukarramah,21.4267,39.8261,65.98,42,0,5.23,SA,1612053410
165,Karasburg,-28.0167,18.7500,68.88,41,0,6.96,NaN,1612053569
183,Dwārka,22.2394,68.9678,64.53,45,0,9.57,IN,1612053572
228,Kahului,20.8947,-156.4700,78.80,57,40,18.41,US,1612053440
246,Mahād,18.0833,73.4167,70.74,40,0,4.05,IN,1612053584
273,Te Anau,-45.4167,167.7167,65.53,47,29,6.89,NZ,1612053363
334,Rawson,-43.3002,-65.1023,60.66,59,22,14.81,AR,1612053599
359,Coyhaique,-45.5752,-72.0662,64.40,45,0,9.22,CL,1612053348
404,Yeppoon,-23.1333,150.7333,84.20,58,40,12.66,AU,1612053613
405,Codrington,-38.2667,141.9667,65.07,57,0,8.46,AU,1612053445
406,Lehigh Acres,26.6254,-81.6248,68.00,56,20,6.91,US,1612053614
412,Lodwar,3.1191,35.5973,77.23,39,0,8.01,KE,1612053615
420,Concepción del Oro,24.6333,-101.4167,61.16,32,0,6.33,MX,1612053616
436,Tomatlán,19.9333,-105.2500,76.41,54,0,5.03,MX,1612053619
441,Esmeraldas,-19.7625,-44.3139,78.80,57,0,8.05,BR,1612053477
488,Emerald,-23.5333,148.1667,86.00,48,40,5.75,AU,1612053629
497,Viedma,-40.8135,-62.9967,62.01,57,24,10.71,AR,1612053443
546,Dargaville,-35.9333,173.8833,73.47,43,0,7.72,NZ,1612053639
566,Comodoro Rivadavia,-45.8667,-67.5000,60.80,51,0,8.05,AR,1612053596
569,Paihia,-35.2822,174.0912,73.00,56,0,11.01,NZ,1612053352

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# Add a "Hotel Name" column to dataframe
hotel_df["Hotel Name"] = ""
hotel_df.head()

<ipython-input-7-9bb98b001916>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
26,Busselton,-33.6500,115.3333,75.99,58,0,8.48,AU,1612053308,
35,Acajutla,13.5928,-89.8275,80.60,54,20,5.79,SV,1612053354,
60,Thayetmyo,19.3167,95.1833,66.00,45,57,1.30,MM,1612053549,
61,Hobart,-42.8794,147.3294,73.00,40,20,11.50,AU,1612053549,
102,Ahipara,-35.1667,173.1667,72.28,49,0,5.99,NZ,1612053557,

In [39]:
# Set parameters to search for a hotel
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Iterate through 
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "Hotel" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    # convert to json
    name_address = name_address.json()
    
    # Grab the first hotel from the results and store the name
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

hotel_df

C:\Users\carua.DESKTOP-4FTJ629\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
26,Busselton,-33.6500,115.3333,75.99,58,0,8.48,AU,1612053308,Observatory Guest House
35,Acajutla,13.5928,-89.8275,80.60,54,20,5.79,SV,1612053354,asi es
60,Thayetmyo,19.3167,95.1833,66.00,45,57,1.30,MM,1612053549,Htarwaya Thitsar Guest House
61,Hobart,-42.8794,147.3294,73.00,40,20,11.50,AU,1612053549,St Ives Hobart Accommodation Tasmania
102,Ahipara,-35.1667,173.1667,72.28,49,0,5.99,NZ,1612053557,Ahipara Holiday Park
103,Ratnagiri,16.9833,73.3000,73.20,50,2,5.84,IN,1612053557,Hotel Landmark
107,Broken Hill,-31.9500,141.4333,77.00,38,8,13.80,AU,1612053557,Royal Exchange Hotel
118,Fortuna Foothills,32.6578,-114.4119,64.40,34,1,9.22,US,1612053560,Fortuna De Oro RV Park
122,Mildura,-34.2000,142.1500,75.00,53,0,9.22,AU,1612053560,Mercure Hotel Mildura
153,Wanaka,-44.7000,169.1500,70.50,36,17,5.99,NZ,1612053566,Wanaka Homestead Lodge and Cottages
156,Makkah al Mukarramah,21.4267,39.8261,65.98,42,0,5.23,SA,1612053410,"Makkah Clock Royal Tower, A Fairmont Hotel"
165,Karasburg,-28.0167,18.7500,68.88,41,0,6.96,NaN,1612053569,Hoon's Selfcatering
183,Dwārka,22.2394,68.9678,64.53,45,0,9.57,IN,1612053572,Hotel Narayan Avezika Comfort
228,Kahului,20.8947,-156.4700,78.80,57,40,18.41,US,1612053440,Maui Seaside Hotel
246,Mahād,18.0833,73.4167,70.74,40,0,4.05,IN,1612053584,Hotel Saitej
273,Te Anau,-45.4167,167.7167,65.53,47,29,6.89,NZ,1612053363,Kingsgate Hotel Te Anau
334,Rawson,-43.3002,-65.1023,60.66,59,22,14.81,AR,1612053599,Hosteria Sampedro
359,Coyhaique,-45.5752,-72.0662,64.40,45,0,9.22,CL,1612053348,Diego De Almagro Coyhaique
404,Yeppoon,-23.1333,150.7333,84.20,58,40,12.66,AU,1612053613,Villa Mar Colina
405,Codrington,-38.2667,141.9667,65.07,57,0,8.46,AU,1612053445,Codrington Gardens Bed And Breakfast
406,Lehigh Acres,26.6254,-81.6248,68.00,56,20,6.91,US,1612053614,Lehigh Resort Club
412,Lodwar,3.1191,35.5973,77.23,39,0,8.01,KE,1612053615,Turkwel Lodge
420,Concepción del Oro,24.6333,-101.4167,61.16,32,0,6.33,MX,1612053616,HOTEL HACIENDA SAN JAVIER
436,Tomatlán,19.9333,-105.2500,76.41,54,0,5.03,MX,1612053619,Norma franco
441,Esmeraldas,-19.7625,-44.3139,78.80,57,0,8.05,BR,1612053477,Bom Será - Marcinho e Fernanda
488,Emerald,-23.5333,148.1667,86.00,48,40,5.75,AU,1612053629,The Irish Village
497,Viedma,-40.8135,-62.9967,62.01,57,24,10.71,AR,1612053443,Hotel Cristal
546,Dargaville,-35.9333,173.8833,73.47,43,0,7.72,NZ,1612053639,Parkview Motel
566,Comodoro Rivadavia,-45.8667,-67.5000,60.80,51,0,8.05,AR,1612053596,Austral Hotel
569,Paihia,-35.2822,174.0912,73.00,56,0,11.01,NZ,1612053352,Copthorne Hotel and Resort Bay of Islands

In [45]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [63]:
hotels= hotel_df["Hotel Name"].tolist()
hotels

['Observatory Guest House',
 'asi es',
 'Htarwaya Thitsar Guest House',
 'St Ives Hobart Accommodation Tasmania',
 'Ahipara Holiday Park',
 'Hotel Landmark',
 'Royal Exchange Hotel',
 'Fortuna De Oro RV Park',
 'Mercure Hotel Mildura',
 'Wanaka Homestead Lodge and Cottages',
 'Makkah Clock Royal Tower, A Fairmont Hotel',
 "Hoon's Selfcatering",
 'Hotel Narayan Avezika Comfort',
 'Maui Seaside Hotel',
 'Hotel Saitej',
 'Kingsgate Hotel Te Anau',
 'Hosteria Sampedro',
 'Diego De Almagro Coyhaique',
 'Villa Mar Colina',
 'Codrington Gardens Bed And Breakfast',
 'Lehigh Resort Club',
 'Turkwel Lodge',
 'HOTEL HACIENDA SAN JAVIER',
 'Norma franco',
 'Bom Será - Marcinho e Fernanda',
 'The Irish Village',
 'Hotel Cristal',
 'Parkview Motel',
 'Austral Hotel',
 'Copthorne Hotel and Resort Bay of Islands']

In [60]:
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=[f"Hotels: {hotels}" for Name in hotel_info]
)


fig = gmaps.figure()
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [62]:
# Add marker layer ontop of heat map
#gmaps.configure(api_key=g_key)

# Display figure
fig=gmaps.figure()
fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:




# for idx, each_row in hotel_df.iterrows():
#     complete_url= f'{base_url}address={cities}&key=g_key'
#     response=requests.get(complete_url)
#     data=response.json()





# base_url= "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"
#response = requests.get(f"http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={weather_api_key}&units=Imperial").json()
 #       city.append(response['name'])
#for idx, each_row in hotel_df.head(5).iterrows():
  
#     query_param= {
#     'key': g_key,
#     'location':f"{each_row['Lat'], each_row['Lng']}",
#     'radius': 5000,
#     'type': 'lodging'
# }
# response=requests.get(base_url, query_param)
    
    
#complete_url=f'{base_url}address={each_row["City"]}, {each_row["State"]}&key={g_key}'
#data=response.json(),

# query_url= (f"{base_url}, {query_param}, &key={g_key}")

# response = requests.get(f"{query_url}&key={g_key}")
#response= requests.get(base_url, query_param, g_key)

In [42]:
# params = {
#     "radius": 5000,
#     "types": "lodging",
#     "key": g_key
# }

# # Iterate through 
# for index, row in hotel_df.iterrows():
#     # get lat, lng from df
#     lat = row["Lat"]
#     lng = row["Lng"]
    
#     params["location"] = f"{lat},{lng}"
#     base_url= "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"
#     response = requests.get(base_url, params=params)  
#     data=response.json()
    
#     try: 
#         row.loc[index, "Hotel Name"]= data["results"][0]["name"]
#     except: 
#         print("City not found. Skipping...")
#         pass 
# hotel_df.head()

In [ ]:

#for idx, each_row in weather_df.iterrows():
# params = {
 #   "radius": target_radius
#}
# lat= hotel_df.loc['Lat']
# lng= hotel_df.loc['Lng']
#city_name= hotel_df['City']

In [40]:
# query_params={
#     'key': g_key,
#    # 'location': city,
#     'radius': 5000,
#     'types': 'lodging'   
# }

# for idx, each_row in hotel_df.iterrows():
#     try:
#         lat= each_row["Lat"]
#         lon= each_row["Lng"]
#         #city= (f"{lat},{lon}")
#         query_params['location'] = f"{lat},{lng}"
#         base_url= "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"
#         response = requests.get(base_url, params=query_params)  
#         data=response.json()
#         each_row.loc[index, "Hotel Name"]= data["results"][0]["name"]
#     except: 
#         print("City not found. Skipping...")
#         pass 
# hotel_df.head()

In [41]:
# # city=city_name.tolist()

# # base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# base_url= "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"
# for idx, each_row in hotel_df.iterrows():
#     try:
#         lat= each_row["Lat"]
#         lon= each_row["Lng"]
#         city= (f"{lat},{lon}")

#         query_params={
#             'key': g_key,
#         #    'location': city,
#             'radius': 5000,
#             'types': 'lodging'  
#         }
#         response = requests.get(base_url, params=query_params)  
#         data=response.json()
        
        
#         each_row.loc[index, "Hotel Name"]= data["results"][0]["name"]
#        # hotel_name= each_row["Hotel Name"]
#     except: 
#         print("City not found. Skipping...")
#         pass 

# # for idx, each_row in hotel_df.iterrows():
# #     lat= each_row["Lat"]
# #     lon= each_row["Lng"]
# #     city= (f"{lat},{lon}")

# #     query_params={
# #     'key': g_key,
# #     'location': city,
# #     'radius': 5000,
# #     'types': 'lodging'   
# #     }

# #     base_url= "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"
# #     response = requests.get(base_url, params=query_params)  
# #     data=response.json()

# #     try:
# #         each_row.loc[index, "Hotel Name"]= data["results"][0]["name"]
# # #hotel_name= each_row["Hotel Name"]
# #     except: 
# #         print("City not found. Skipping...")
# #         pass 
# hotel_df.head()

#     # hotel_name= each_row["Hotel Name"]
    
# #pprint(data)
#  #   response=requests.get(complete_url)
    
    
# #query_param
# # for idx, each_row in hotel_df(3).iterrows():
# #     complete_url=f'{base_url}{query_param}'

# # for idx, each_row in hotel_df():

# # for idx, each_row in hotel_df(3).iterrows():
# #     query_param={
# #         'key': g_key,
# #         'location': {each_row['City']},
# #         'radius': 5000,
# #         'type': 'lodging'
# #     }

# #response=requests.get(base_url, query_param)

#    # 'location': {each_row['City']},
# # pprint(response.json())
# #response=requests.get(gmaps.configure(api_key=g_key))